#!/bin/sh
#
echo("When the moon hits your eye like a big pizza pie")
echo("Thats amore")
echo("When the world seems to shine like you've had too much wine")
echo("That's amore")
echo("Bells will ring ting-a-ling-a-ling, ting-a-ling-a-ling")
echo("And you'll sing Vita bella")
echo("Hearts will play tippy-tippy-tay, tippy-tippy-tay")
echo("Like a gay tarantella")
echo("When the stars make you drool just like a pasta e fasul")
echo("That's amore")
echo("When you dance down the street with a cloud at your feet")
echo("You're in love")
echo("When you walk in a dream but you know you're not dreaming signore")
echo("Scusami, but you see, back in old Napoli")
echo("That's amore")
echo("When the moon hits your eye like a big pizza pie, that's amore")
echo("That's amore,")
echo("When the world seems to shine like you've had too much wine, that's amore")
echo("That's amore")
echo("Bells will ring ting-a-ling-a-ling, ting-a-ling-a-ling")
echo("And you'll sing Vita bella (Vita bel-, vita bella)")
echo("Hearts will play tippy-tippy-tay, tippy-tippy-tay")
echo("Like a gay tarantella")
echo("Lucky fella")
echo("When the stars make you drool just like a pasta e fasul, that's amore")
echo("That's amore")
echo("When you dance down the street with a cloud at your feet")
echo("You're in love")
echo("When you walk in a dream but you know you're not dreaming signore")
echo("Scusami, but you see, back in old Napoli")
echo("That's amore")
echo("Amore, that's amore")